
 BKETH Error at 29/06/2021 16:56:16 
Error:HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000179603301C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))(MaxRetryError("HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000179603301C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"),)
 BKETH Error at 29/06/2021 16:56:16 
Error:HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001796015A520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))(MaxRetryError("HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001796015A520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"),)
 BKETH Error at 29/06/2021 16:56:16 
Error:HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000179601A0A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))(MaxRetryError("HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000179601A0A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"),)
 BKETH Error at 29/06/2021 16:56:16 
Error:HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000179601A0F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))(MaxRetryError("HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000179601A0F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"),)
 BKETH Error at 29/06/2021 16:56:16 
Error:HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017960191CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))(MaxRetryError("HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /trade/order (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017960191CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"),)
 BKETH Error at 30/06/2021 10:11:01 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 01/07/2021 21:39:15 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 03/07/2021 02:15:33 
Error:('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)),)
 BKETH Error at 03/07/2021 02:15:35 
Error:('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)),)
 BKETH Error at 05/07/2021 19:11:37 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 08/07/2021 03:49:19 
Error:('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)),)
 BKETH Error at 08/07/2021 04:04:59 
Error:('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)),)
 BKETH Error at 08/07/2021 13:15:55 
Error:HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /authentication/user_authentication/exchangeToken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E6D208A7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))(MaxRetryError("HTTPSConnectionPool(host='api.cryptosrvc.com', port=443): Max retries exceeded with url: /authentication/user_authentication/exchangeToken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E6D208A7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"),)
 BKETH Error at 09/07/2021 05:28:36 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 09/07/2021 15:15:34 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 09/07/2021 15:23:44 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 09/07/2021 21:29:44 
Error:Expecting value: line 1 column 1 (char 0)('Expecting value: line 1 column 1 (char 0)',)
 BKETH Error at 11/07/2021 23:39:51 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 12/07/2021 03:04:57 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 12/07/2021 14:15:07 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 12/07/2021 15:06:33 
Error:'client_access_token'('client_access_token',)
 BKETH Error at 13/07/2021 10:45:15 
Error:'client_access_token'('client_access_token',)